### ISSUE TITLE
"Nested NER" Intuition behind "nested" and when to use

### ISSUE THREAD

**Issue by krumeto** [urchade/GLiNER#65]
Hi and thank you for the fantastic models! Could you please comment on the intuition behind "nested ner"? I am mostly interested in some rule of thumb when to use it or not.

I found the below in the paper:
```
Flat NER: The algorithm chooses the highest scoring non-overlapping span and continues this
process until all spans are evaluated.
Nested NER: Similar to Flat NER, but the algorithm allows selection of fully nested spans within
other entities while still avoiding partial overlaps.
```
If understand correctly,  "Nested NER" allows for an entity to be overlapping with other entity (I am not sure if that's correct). If my understanding is correct, it seems like most of the cases, a flat NER would be a good default.

Would love to get your thoughts. Thank you in advance!

**Comment by tomaarsen** [comment]
That is correct, nested NER allows for overlaps, such that a word can be a part of multiple spans.
You can experiment with this by checking out a demo:
* https://huggingface.co/spaces/tomaarsen/gliner_medium-v2.1
* https://huggingface.co/spaces/urchade/gliner_multiv2.1

and putting the threshold quite low (e.g. 0.2) while enabling Nested NER. What you'll see is that some spans get "duplicated" (because the annotated text widget in Gradio doesn't work well with nested spans 😄). E.g. nested:
![image](https://github.com/urchade/GLiNER/assets/37621491/58892e7b-2283-4971-89bc-3a8c6ab4630e)

and non-nested:
![image](https://github.com/urchade/GLiNER/assets/37621491/d6d88724-9368-4c7a-a976-2fdbdabb5753)

- Tom Aarsen
