### ISSUE TITLE
Integration of negspacy with the current model

### ISSUE THREAD

**Issue by shyamalaspure** [urchade/GLiNER#90]
I am working on medical entities extraction on some report text using GLiNER spacy. 
Is t there any way I can integrate below code with current extraction logic.
Current model I am using `en_core_sci_sm`

```
from negspacy.negation import Negex
import spacy
from negspacy.termsets import termset

nlp = spacy.load("en_core_sci_sm")
ts = termset("en_clinical")
nlp.add_pipe(
    "negex",
    config={
        "neg_termset":ts.get_patterns(),
#         "chunk_prefix": ["no"],
    },
    last=True,
)
```

**Comment by wjbmattingly** [comment]
Hi! Sorry for my delay on this. I don't always see the GliNER spaCy questions here. If you submit an issue in the GliNER spaCy repository, I'd be more than happy to keep the conversation going there so that you receive proper credit.

More than happy to help here, though. I have not worked with `en_core_sci_sm` yet or negspacy. I don't see why this would be an issue having just looked quickly at the docs. I build GliNER spaCy to be highly malleable to future updates of GliNER and different languages and use cases, meaning it works with any GliNER model and any spaCy pipeline. In doing this, though, you need to make a design decision on where GliNER will sit in your spaCy pipeline. If you want to give GliNER priority, then I'd place it before the NER component of `en_core_sci_sm`. If you want it to fill in the gaps, then place it after. Another option would be to set the gliner_spacy component's style to "span" which puts the outputs in doc.spans["sc"].  Negspacy may require you to have these spans in doc.ents, though.

**Comment by shyamalaspure** [comment]
`en_core_sci_sm` is the model used for entity extraction, I need to replace it with GliNER one `gliner_large_bio-v0.1` using spacy pipeline. Anyways got the success to add this and with some good results. I will post the soultion here if anyone needed.

**Comment by wjbmattingly** [comment]
Ah, thanks so much! Glad to hear you got it all working. Would you be willing to create a folder called examples and submit a notebook as a PR for showing how to use it for others? https://github.com/theirstory/gliner-spacy

**Comment by shyamalaspure** [comment]
@wjbmattingly sure will be happy to contribute.

**Comment by wjbmattingly** [comment]
Awesome! Thanks! =)
